### ISSUE TITLE
Groups not working after most recent update

### ISSUE THREAD

**Issue by SephirothFF7R** [blaxxun-boop/Groups#13]
Can no longer form groups and commands are not recognized.

**Comment by blaxxun-boop** [comment]
Means you are using Valheim Plus. Moving forward, no mods from me will work with Valheim Plus.

**Comment by SephirothFF7R** [comment]
Oh....may I ask why? We use a lot of mods from you so I'm guessing we just won't be updating them anymore?

**Comment by Malus565** [comment]
yeah i thought one of the Valheim Plus mod authors reached out to you for another mod to assist with the issue.  Valheim Plus has so many features that work great and not easy to replace.

**Comment by blaxxun-boop** [comment]
@SephirothFF7R It's not just me, other mod authors will follow. And mods tend to break with Valheim updates, so not updating mods anymore is hardly an option. You might wanna look into dropping Valheim Plus.

@Malus565 Yes, they've reached out to me a couple of times, always promising they will fix the issues soon. Some of the issues I've reported to them will turn 2 years old soon. I provided clear instructions on how to fix them and they've promised to fix them as soon as possible, and yet here we are. So, that's usually just a lot of hot air, nothing else.
And there is nothing in Valheim Plus that cannot be easily replaced by another mod, which also happens to do it way better than Valheim Plus. It's a jack of all trades, master of none type of thing.

**Comment by psyferre** [comment]
@blaxxun-boop : Thanks for all the great mods!  I've added a bug to the issue tracker for V+ and will try to frequently mention it in their discord, in hopes that some sort of traction can be gained.  /shrug

**Comment by psyferre** [comment]
@blaxxun-boop: A dev for V+has responded to my ticket and seems open to resolving issues if they can get more information.  As I said on that thread, I'm a developer - but not for Unity.  That said, I'd be happy to help any way I can in making progress.  Would you be willing to talk with them to see if the issue(s) can be resolved?  

Obviously, a lot of players love your mods and are caught in the middle between those and V+, which for better or worse is almost a given on any modded server.  I'd love to see a resolution and I'm willing to help make it happen if I can.

**Comment by Malus565** [comment]
@psyferre Thanks for making the effort to get this resolved.  Very much appreciated!

**Comment by blaxxun-boop** [comment]
@psyferre You are wasting your time. I have no intention to make any of my mods ever work with Valheim Plus again.

I've reported several issues to the V+ devs over the past two years. They always promised to fix the issues as soon as possible. Some of the issues I've reported, including the solution on how to fix them, turn 2 years old soon. It's just a lot of hot air. The Valheim Plus devs have said that they want Valheim Plus to be the only mod that people use several times now and it shows in their actions. They don't give a damn about compatibility with other mods. The bridges are burned. Valheim Plus is a disease in the modding community and needs to go.

More info: https://github.com/blaxxun-boop/PassivePowers/issues/5

**Comment by psyferre** [comment]
That's disappointing to hear, but thank you for your candor.  Best of luck to you.

**Comment by SephirothFF7R** [comment]
Yeah V+ is literally so ingrained onto people that no one ever seems to realize there are other options out there.

I used V+ on my server till recently. It wasn't super hard to find alternatives. I don't like how V+ is treated as some "my way or the highway" mod. That's just being selfish of them.

Use OdinsQOL mod. It has many of the same features as V+ did and may serve as a starting point for you folks to migrate to.

**Comment by psyferre** [comment]
Thanks for pointing me to OdinsQOL, @SephirothFF7R.  While it's missing quite a few things that we use, it's a great starting point.

@blaxxun-boop:  I closed the ticket I opened on V+ after you told me I was wasting my time.  For what it's worth, Healiha re-opened the ticket saying they hadn't been able to work on the issues since the last time they spoke with you, and admitted there were some poorly designed portions of their codebase.  They're still interested in trying to improve compatibility.  https://github.com/valheimPlus/ValheimPlus/issues/764

Did you change your username at any point?  No one can seem to find any of the issues you've submitted.  If we could find those it would help in making the compatibility changes in V+, and show that they've been lax in responding to other mod devs.  To be frank, I started on this quest of trying to get everyone connected because I felt bad that you were being driven to such extremes by the "big bad mod on campus", but now I've just stirred up everyone for no reason and can't find any support for your position. :-/

**Comment by King-of-Blades** [comment]
TBH V+ doesn't look like the bad guy here.  Maybe behind the scenes they do, but so far there's been no actual evidence of them doing anything wrong shown, other than the claims that they inconvenience other devs.  I've also failed to find any evidence of these supposed issues that have been ignored for years.

I'm not interested in supporting someone that would lie for their own gain and to try and push another dev out of the modding ecosystem, so anything to back up the claims would be appreciated, as I'd rather not have to take sides here.  Till then I'll continue making personal edits to undo the incompatibility.

**Comment by blaxxun-boop** [comment]
@psyferre I did not change my username, no. These conversations happened in DMs, mostly wiith nx, but with other V+ devs as well.

@King-of-Blades Please note that no license on GitHub means only looking, no touching. Doing stuff like that is a great way to make sure mod devs will keep their repos private in the future and their code obfuscated. I won't do that, since I am a strong defender of open source code, but I definitely know that others will.

And yes, a lot of that shit show happens internally. As I said already, the V+ devs always tell people that they are willing to change and make their stuff compatible to the people on the outside. Internally, they are essentially a huge bully in the modding community and tell other modders that V+ is the only mod that people should use anyway and don't care about other mods at all.
Just join one of the active Valheim modding Discord servers (other than the V+ one, obviously) and talk to the mod authors there. You will always hear the same story.

**Comment by King-of-Blades** [comment]
@blaxxun-boop 

[No license actually means that no one is legally permitted to to download, use, modify, or share your mods at all.](https://choosealicense.com/no-permission/)  You're right about "no touching", but touching includes installing and running the mods as intended in the game too.  Currently the only people legally allowed to make use of your code are those who have actually negotiated licenses with you, and I suspect that number is a fat zero.

Seeing as we're all violating your license every time we play the game and use your mods to begin with, might as well make the edits needed since a violation is a violation is a violation.

**Comment by blaxxun-boop** [comment]
@King-of-Blades No, because if I upload a compiled version of my mod to Thunderstore, I give Thunderstore the permission to distribute my mods and users that download my mods from Thunderstore the permission to use my mods.

**Comment by King-of-Blades** [comment]
@blaxxun-boop 

Thunderstore has no ToS or any other form of agreement when you upload a mod, therefore, legally speaking, you haven't given permission for anything past them hosting the mod.  They even have a 'add ToS for mod permissions' in their backlog on their tasklist.  

Your license still applies on Thunderstore, because there's no extant agreement to give them a more permissive use of your code.

**Comment by SephirothFF7R** [comment]
> @blaxxun-boop
> 
> Thunderstore has no ToS or any other form of agreement when you upload a mod, therefore, legally speaking, you haven't given permission for anything past them hosting the mod. They even have a 'add ToS for mod permissions' in their backlog on their tasklist.
> 
> Your license still applies on Thunderstore, because there's no extant agreement to give them a more permissive use of your code.

You need to chill sir and just move on. You're being pissy and you're acting just as conceited as the V+ devs.

If you wanna use this guys mods, get rid of V+. End of story. Don't wanna get rid of V+? Then suck it up and count your losses. They're his mods and he can do with them as he pleases.

Now...if you don't mind, please kindly go fuck off.

**Comment by SephirothFF7R** [comment]
> @blaxxun-boop
> 
> Thunderstore has no ToS or any other form of agreement when you upload a mod, therefore, legally speaking, you haven't given permission for anything past them hosting the mod. They even have a 'add ToS for mod permissions' in their backlog on their tasklist.
> 
> Your license still applies on Thunderstore, because there's no extant agreement to give them a more permissive use of your code.

You need to chill sir and just move on. You're being pissy and you're acting just as conceited as the V+ devs.

If you wanna use this guys mods, get rid of V+. End of story. Don't wanna get rid of V+? Then suck it up and count your losses. They're his mods and he can do with them as he pleases.

Now...if you don't mind, please kindly go fuck off.

**Comment by Malus565** [comment]
@King-of-Blades you don't have to like the fact they add the incompatibility and you have every right to disagree with it. I completely understand as I enjoy using V+ and also enjoy using using @blaxxun-boop mods as well.  But don't come on here blasting them, that doesn't help anything.  You know they also go through their own frustrations trying to create wonderful mods that run into bugs from another mod they don't have control of.  Now with that said one of the more active devs from the V+ side has reached out recently and apologized that they hadn't been able to make the changes and even acknowledged they know what the issues are, including old and bad code.  They are hoping to get it updated soon but have been slammed with work.  If they keep to promise and present that to the community, its more than likely the incompatibility will be removed.  Just have to be patient and wait, if your unable to be patient, make your own changes or feel free to use other mods.

**Comment by psyferre** [comment]
For what it's worth, two of the V+ devs have voiced their willingness to work on incompatibility.  I talked for a while with @healiha, and they seemed genuinely hurt to be cast as a bully.  healiha admitted that there was a lot of old code that needed to be updated and better written.  I offered to help if it was within my skillset, and they took some time to actually explain to me some of the more basic changes that need to be made to improve compatibility.  I plan to make use of that knowledge as soon as I can clear some time in my own schedule.  

I went to both parties to try to make peace and do what I could to help make this situation better for all involved.  There, I found kindness and regret, and my efforts were welcomed.  I'll take the advice here that I'm "wasting my time" and put that time where it might make a difference.  I've uninstalled Groups for now, but I hope that someday I can install it again.

**Comment by Malus565** [comment]
Thanks @psyferre , yeah @healiha was exactly the person I was referring about, just couldn't recall his id lol.  Also thanks @blaxxun-boop for the great mods and hard work, which is appreciated.  Thanks @healiha for doing your part to help out with the issues on V+ code, that means a lot to us in the community, cause we love seeing both mods working well together and compatibility issues being ironed out, and excited to see the issues resolved(hopefully soon, given that time allows you). :)
